In [1]:
import numpy as np

In [4]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [11]:
b=np.zeros((3,5))
print(b)
#b

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
b=np.ones((5,5))
#b

In [39]:
np.random.randint(0,1000,(2,2,2,2))

array([[[[ 57, 520],
         [845, 635]],

        [[106, 298],
         [342, 596]]],


       [[[996,  57],
         [ 63, 305]],

        [[836, 710],
         [959, 924]]]])

In [73]:
np.random.seed(102)

arr=np.random.randint(0,1000,(2,2))

print(arr)
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.argmin())
print(arr.argmax())
print(arr.mean())
arr.reshape(1,4)


[[256 755]
 [590 242]]
755
242
1843
3
1
460.75


array([[256, 755, 590, 242]])

In [75]:
mat=np.arange(0,100).reshape(10,10)
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
mat[2][2]

22

In [78]:
mat[0,:]# extract whole row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])